<!DOCTYPE HTML>
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Главное меню родителя</title>
  <style>
    .center-block {
        margin: 50px auto;
        width: 60%;
        padding: 20px;
        font-size: 25px;
    }
    p { text-indent: 75px; }
  </style>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 </head>
 <body>
    <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
              <li class="nav-item"><a href="/parent-schedule" class="nav-link active" aria-current="page">Записаться на приём</a></li>
              <li class="nav-item"><a href="/info" class="nav-link">Информация</a></li>
            </ul>
        </header>
    <div class="col-xxl-8 my-3 mx-3">
        <button class="btn btn-light rounded-pill px-1 col-xxl-1" id="psyBackBtn" type="button" onclick="location.href='/parent'">Назад</button>
    </div>
    <div class="center-block">
            <p>Методика составления рассказов по картинкам базируется на предположении, что навыки построения связного повествования тесно взаимосвязаны с уровнем когнитивного развития ребенка. В частности, способность создавать целостные истории по серии сюжетных изображений требует задействования таких когнитивных функций, как память, концентрация внимания и умение анализировать ситуации для нахождения логических взаимосвязей и решения проблем.</p>
            <p>Иными словами, тест на составление рассказа по картинкам позволяет не только оценить речевые способности ребенка, но и косвенно судить о степени сформированности важных мыслительных процессов - зрительной и вербальной памяти, распределения внимания, аналитического мышления. Создание связной истории предполагает удержание в памяти деталей изображений, концентрацию внимания на сюжетных линиях, выстраивание логических связей между событиями для преодоления возникающих "проблем" в повествовании.</p>
            <p>Во время индивидуального тестирования ребенку предлагается рассмотреть сюжет из нескольких картинок, а затем составить по ним свой небольшой рассказ.</p>
            <p>Для оценки результатов теста по составлению рассказов используется система, разработанная Т.В. Ахутиной.</p>
        </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 </body>
</html>