<!DOCTYPE HTML>
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Авторизация</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 </head>
 <body>
    <div class="col-lg-6 col-xxl-3 my-5 mx-auto">
        <div class="d-grid gap-2">
            <h1 align="center" class="display-5 fw-bold text-body-emphasis">Авторизация</h1>
        </div>
      </div>
    <div class=" col-lg-6 col-xxl-4 my-5 mx-auto">
        <div class="d-grid gap-2">
          <button class="btn btn-outline-secondary" id="loginAsParentBtn" type="button" onclick="location.href='/parent'">Войти как родитель</button>
          <button class="btn btn-primary" id="loginAsPsychologistBtn" type="button" onclick="location.href='/psychologist'">Войти как психолог</button>
        </div>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 </body>
</html>